### ISSUE TITLE
com.hierynomus.smbj.common.SMBRuntimeException: DiskShare has already been closed

### ISSUE THREAD

**Issue by Invenio-Kalesha** [josephgonzales01/mule4-smb-connector#7]
I am getting following intermittent exception while connecting to shared network drive

Root Exception stack trace:
com.hierynomus.smbj.common.SMBRuntimeException: DiskShare has already been closed
        at com.hierynomus.smbj.share.Share.send(Share.java:351)
        at com.hierynomus.smbj.share.Share.sendReceive(Share.java:345)
        at com.hierynomus.smbj.share.Share.createFile(Share.java:159)
        at com.hierynomus.smbj.share.DiskShare.createFileAndResolve(DiskShare.java:97)
        at com.hierynomus.smbj.share.DiskShare.resolveAndCreateFile(DiskShare.java:79)
        at com.hierynomus.smbj.share.DiskShare.open(DiskShare.java:66)
        at com.hierynomus.smbj.share.DiskShare.exists(DiskShare.java:187)
        at com.hierynomus.smbj.share.DiskShare.folderExists(DiskShare.java:183)
        at com.wsl.smbConnector.internal.service.SMBWriteOperationService.perform(SMBWriteOperationService.java:40)
        at com.wsl.smbConnector.internal.SmbOperations.write(SmbOperations.java:78)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:282)
        at org.mule.runtime.module.extension.internal.runtime.execution.ReflectiveMethodComponentExecutor.lambda$execute$1(ReflectiveMethodComponentExecutor.java:80)
        at org.mule.runtime.core.api.util.ExceptionUtils.tryExpecting(ExceptionUtils.java:227)
        at org.mule.runtime.core.api.util.ClassUtils.withContextClassLoader(ClassUtils.java:915)
        at org.mule.runtime.core.api.util.ClassUtils.withContextClassLoader(ClassUtils.java:879)
        at org.mule.runtime.module.extension.internal.runtime.execution.ReflectiveMethodComponentExecutor.execute(ReflectiveMethodComponentExecutor.java:79)
        at org.mule.runtime.module.extension.internal.runtime.operation.ReflectiveMethodOperationExecutor.execute(ReflectiveMethodOperationExecutor.java:64)
        at org.mule.runtime.module.extension.internal.runtime.execution.InterceptableOperationExecutorWrapper.execute(InterceptableOperationExecutorWrapper.java:60)
        at org.mule.runtime.module.extension.internal.runtime.operation.DefaultExecutionMediator.lambda$null$3(DefaultExecutionMediator.java:146)
        at org.mule.runtime.core.api.util.ExceptionUtils.tryExpecting(ExceptionUtils.java:227)
        at org.mule.runtime.core.api.util.ClassUtils.withContextClassLoader(ClassUtils.java:915)
        at org.mule.runtime.core.api.util.ClassUtils.withContextClassLoader(ClassUtils.java:879)
        at org.mule.runtime.module.extension.internal.runtime.operation.DefaultExecutionMediator.lambda$executeWithInterceptors$9(DefaultExecutionMediator.java:146)
        at reactor.core.* (20 elements filtered from stack; set debug level logging or '-Dmule.verbose.exceptions=true' for everything)(Unknown Source)
        at org.mule.runtime.core.privileged.processor.chain.* (2 elements filtered from stack; set debug level logging or '-Dmule.verbose.exceptions=true' for everything)(Unknown Source)
        at reactor.core.* (4 elements filtered from stack; set debug level logging or '-Dmule.verbose.exceptions=true' for everything)(Unknown Source)
        at org.mule.runtime.core.privileged.processor.chain.* (1 elements filtered from stack; set debug level logging or '-Dmule.verbose.exceptions=true' for everything)(Unknown Source)
        at reactor.core.* (11 elements filtered from stack; set debug level logging or '-Dmule.verbose.exceptions=true' for everything)(Unknown Source)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.mule.service.scheduler.internal.AbstractRunnableFutureDecorator.doRun(AbstractRunnableFutureDecorator.java:111)
        at org.mule.service.scheduler.internal.RunnableFutureDecorator.run(RunnableFutureDecorator.java:54)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**********************************************************************

**Comment by Invenio-Kalesha** [comment]
I am using mulesoft CE 4.2.0 and Jdk8
